---
# tasks file for kibana
- name: import elasticsearch gpg key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: add elastic repository
  yum_repository:
    name: "kibana-4.5"
    description: Kibana repository for 4.5.x packages
    file: elastic
    baseurl: http://packages.elastic.co/kibana/4.5/centos
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: yes

- name: install kibana
  yum: name=kibana-{{ kibana_version }} state=installed

#- name: put elasticsearch config
#  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644
#  notify:
#    - restart elasticsearch

- name: start kibana
  service: name=kibana state=started enabled=yes
